# AI Summary: GitHub Actions workflow building the wheel, installing it into an
# isolated conda environment, running the test‑suite, and performing a smoke‑
# test across Python 3.10–3.12 to ensure the distributed package works end‑to‑end.
name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up base Python (for build tools)
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel

      - name: Build sdist & wheel
        run: python -m build --sdist --wheel --outdir dist/

      # ---------------------------------------------------------------------#
      # Create a fresh *conda* environment for installation and testing      #
      # ---------------------------------------------------------------------#
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          activate-environment: test-env

      - name: Install wheel and test dependencies
        shell: bash -l {0}
        run: |
          pip install --upgrade pip
          pip install dist/*.whl
          pip install pytest

      - name: Run unit tests (installed wheel)
        shell: bash -l {0}
        run: pytest -q

      - name: Smoke‑test SVBMC optimize()
        shell: bash -l {0}
        run: |
          python - <<'PY'
          import svbmc, numpy as np

          class _Identity:
              def __call__(self, x): return x
              def inverse(self, x): return x
              def log_abs_det_jacobian(self, x):
                  import numpy as np
                  return np.zeros(x.shape[0]) if isinstance(x, np.ndarray) else 0.0

          class _MockVP:
              def __init__(self):
                  self.mu = np.zeros((2, 1))
                  self.sigma = np.ones((2, 1))
                  self.lambd = np.ones((2, 1))
                  self.w = np.ones(1)
                  self.stats = {"I_sk": np.ones((5, 1)), "elbo": 0.0, "stable": True, "J_sjk": 0.1*np.eye(1)}
                  self.parameter_transformer = _Identity()
              def sample(self, n):
                  return np.zeros((n, 2)), None

          vp = _MockVP()
          svbmc.SVBMC([vp]).optimize(version="ns", n_samples=5)
          print("Smoke‑test completed successfully.")
          PY
    